### PR TITLE
test: throw on deprecation

### PR DESCRIPTION
**Pull request by JustinBeckwith**

### CODE REVIEW

**Comment by alexander-fenster** [comment]
why me? :)

**Comment by JustinBeckwith** [comment]
Ah!  Good question.  If you look at the failure, it's because of the way we're using grpc from gax :)

**Comment by alexander-fenster** [comment]
Ah! I see.

**Comment by alexander-fenster** [comment]
Will be fixed in https://github.com/googleapis/gax-nodejs/issues/286, and needs to be tested in a branch first.

**Pull request merged**
